apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres (base64 encoded)
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password (base64 encoded)
